version: "3"

services:
  # producer
  producer:
    image: kfkhademo/producer:0.1
    build:
      context: ./app/producer
      dockerfile: Dockerfile
    environment: 
      - PRODUCER_DELAY=0.01
      - START_DELAY=60
    depends_on:
      - grafana
    networks:
      kfk-ha:
    restart: always

  # consumer
  consumer:
    image: kfkhademo/consumer:0.1
    build:
      context: ./app/consumer
      dockerfile: Dockerfile
    environment: 
      - CONSUMER_DELAY=0.01
      - START_DELAY=90
    depends_on:
      - grafana
    networks:
      kfk-ha:
    restart: always

  zk1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk1
    ports:
      - 12181:12181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.10
        aliases:
          - zk1

  zk2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk2
    ports:
      - 22181:22181
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.11
        aliases:
          - zk2

  zk3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk3
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:12888:13888;zk2:22888:23888;zk3:32888:33888
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.13
        aliases:
          - zk3

  # zkwebui:
  #   image: tobilg/zookeeper-webui
  #   ports:
  #     - 8001:8080
  #   environment:
  #     - USER=admin
  #     - PASSWORD=admin
  #     - ZK_DEFAULT_NODE=zk1:2181
  #   networks:
  #     kfk-ha:

  # zkexporter:
  #   image: dabealu/zookeeper-exporter
  #   ports:
  #     - 8002:8080
  #   environment:
  #     - USER=admin
  #     - PASSWORD=admin
  #     - ZK_DEFAULT_NODE=zk1:2181
  #   networks:
  #     kfk-ha:
  #       aliases:
  #         - zkexporter
  #   depends_on:
  #     - zk1
  #     - zk2
  #     - zk3

  # kafka
  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    ports:
      - "19092:19092"
    depends_on:
      - zk1
      - zk2
      - zk3
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    environment:
      JMX_PORT: 9999
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.21
        aliases:
          - kafka1
 
  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    ports:
      - "29092:29092"
    depends_on:
      - zk1
      - zk2
      - zk3
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    environment:
      JMX_PORT: 9999
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.22
        aliases:
          - kafka2
 
  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    ports:
      - "39092:39092"
    depends_on:
      - zk1
      - zk2
      - zk3
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    environment:
      JMX_PORT: 9999
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:12181,zk2:22181,zk3:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092
    networks:
      kfk-ha:
        ipv4_address: 172.25.0.23
        aliases:
          - kafka3

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    command: "--kafka.server=kafka1:19092 --kafka.server=kafka2:29092 --kafka.server=kafka3:39092"
    ports:
      - 9308:9308
    networks:
      kfk-ha:
        aliases:
          - kfkmon
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always

  kafka-manager:
    image: sheepkiller/kafka-manager:alpine
    ports:
      - 9000:9000
    environment:
     - ZK_HOSTS=zk1:12181,zk2:22181,zk3:32181
     - APPLICATION_SECRET=admin
    networks:
      kfk-ha:
        aliases:
          - kfkmgr
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: always

  # monitoring
  prometheus:
    image: prom/prometheus:v2.11.1
    networks:
      kfk-ha:
        aliases:
          - prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-exporter

  grafana:
    image: grafana/grafana:6.2.5
    networks:
      kfk-ha:
    ports:
      - 3000:3000
    environment: 
      - GF_ALERTING_ENABLED:false
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
     - prometheus

  # ipython notebook (for developing kafka demo apps)
  # notebook:
  #   image: ipython/notebook
  #   environment:
  #     - PASSWORD=admin
  #     - USE_HTTP=1
  #   ports:
  #     - 8888:8888
  #   networks:
  #     kfk-ha:
  #   volumes: 
  #     - ./notebooks:/notebooks/

networks:
  kfk-ha:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"

